version: "3.3"
services:
    
    mongo:
        image: mongo
        ports:
        - "27017:27017"

    node_server:
        image: node_server
        build: server/
        volumes:
        - ./:/app
        ports:
         - "3000:3000"
        depends_on: 
        - mongo 
        links:
        - mongo
        
    keycloak:
        image: jboss/keycloak
        ports:
        - "8080:8080"
        environment: 
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
    
    angular:
        image: angular-frontend
        build: .
        ports:
        - "4200:4200"
        links: 
        - keycloak
        - node_server